### ISSUE TITLE
No judges are shown in "Journey deployment" dialog

### ISSUE THREAD

**Issue by nedy13** [jonsito/AgilityContest#2]
In the tracelog there is the following statement which do not match my added judges.

Tracelog: [24-Dec-2015 12:52:31 Europe/Madrid] QUERY juezFunctions::__select() :
SELECT \* FROM Jueces  WHERE 1 AND ((Federations & 768)!=0)   ORDER BY Nombre ASC

Why are the judges not shown in the menu. Which option must be set at the judges itself?
![agilitycontest-judges_001](https://cloud.githubusercontent.com/assets/4283170/11994400/e10ab724-aa3d-11e5-9c38-b1408baaa242.png)
![agilitycontest-judges_002](https://cloud.githubusercontent.com/assets/4283170/11994401/e10eeb00-aa3d-11e5-849d-1009d447924f.png)

Thanks for your help.

**Comment by ghost** [comment]
It's a bug. When international contest is active In the combo boxes should appear every judge marked as "International" or created when an international federation is active

Notice that "international contest" just means "countries" instead of "clubs"

**Comment by ghost** [comment]
Should be fixed now. Please check

**Comment by nedy13** [comment]
Seems to work now.

New query: SELECT \* FROM Jueces  WHERE 1 AND ((Internacional!=0) OR (Federations & 768)!=0)   ORDER BY Nombre ASC

Thank you very much.
