### ISSUE TITLE
exported excel file from Competitors data management dialog is corrupted

### ISSUE THREAD

**Issue by nedy13** [jonsito/AgilityContest#4]
I am not able to open the exported excel file with Excel 2013. I do not know what exactly is broken.

Dialog from where Excel file is generated:
![image](https://cloud.githubusercontent.com/assets/4283170/12374922/a823fa8e-bcac-11e5-9fe0-9100841300f2.png)

Error Excel:
![image](https://cloud.githubusercontent.com/assets/4283170/12374928/d0a153c6-bcac-11e5-8b6a-3473cb900d24.png)

**Comment by jonsito** [comment]
I've using LibreOffice 5 for testing with success
Please check again selecting english as default and some of the include sample contests
( I suspect some i18n issues due to latin1 conversion, but need to check. Especifically: journey names MUST follow standard latin1 charset, as they are used as tab names )

**Comment by jonsito** [comment]
I've updated Spout phpexcel library to version 2.4.1 Please check again

**Comment by nedy13** [comment]
Thank you very much. It is not working, but I am going to check it again, later. I think it could be an environment specific problem, because I created my own federation for testing purposes and to understand the dependencies.
Your tip with Libre Office showed me a new hint:
Strict Standards: Declaration of Excel_Inscripciones::createInfoPage() should be compatible with XLSX_Writer::createInfoPage($title, $federation = -1) in N:\AgilityContest-master\agility\server\excel\inscription_writer.php on line 30

trace.log:
[18-Jan-2016 12:14:44 Europe/Madrid] QUERY excel_printInscripciones::__selectObject() :
SELECT DISTINCT Equipos.\* FROM Equipos,Resultados WHERE (Resultados.Jornada=10) AND (Resultados.Perro=5) AND

```
         (Resultados.Jornada=Equipos.Jornada) AND (Resultados.Equipo=Equipos.ID)
```

[18-Jan-2016 12:14:44 Europe/Madrid] INFO N:\AgilityContest-master\agility\server\excel\inscription_writer.php::132::getTeamByPerro() : El perro 5 no figura en ningun equipo de la jornada 10

[18-Jan-2016 12:14:44 Europe/Madrid] QUERY excel_printInscripciones::__selectObject() :
SELECT \* FROM Equipos WHERE ( Prueba=2 ) AND ( Jornada=10 ) AND (DefaultTeam=1)

[18-Jan-2016 12:14:44 Europe/Madrid] QUERY excel_printInscripciones::__selectObject() :
SELECT DISTINCT Equipos.\* FROM Equipos,Resultados WHERE (Resultados.Jornada=9) AND (Resultados.Perro=1) AND

```
         (Resultados.Jornada=Equipos.Jornada) AND (Resultados.Equipo=Equipos.ID)
```

[18-Jan-2016 12:14:44 Europe/Madrid] QUERY excel_printInscripciones::__selectObject() :
SELECT DISTINCT Equipos.\* FROM Equipos,Resultados WHERE (Resultados.Jornada=10) AND (Resultados.Perro=1) AND

```
         (Resultados.Jornada=Equipos.Jornada) AND (Resultados.Equipo=Equipos.ID)
```

[18-Jan-2016 12:14:44 Europe/Madrid] INFO N:\AgilityContest-master\agility\server\excel\inscription_writer.php::132::getTeamByPerro() : El perro 1 no figura en ningun equipo de la jornada 10

[18-Jan-2016 12:14:44 Europe/Madrid] QUERY excel_printInscripciones::__selectObject() :
SELECT \* FROM Equipos WHERE ( Prueba=2 ) AND ( Jornada=10 ) AND (DefaultTeam=1)

[18-Jan-2016 12:14:44 Europe/Madrid] TRACE N:\AgilityContest-master\agility\server\excel\inscription_writer.php::152::composeTable() : Leave

**Comment by jonsito** [comment]
Ignore this warning: an obsolete notice that indicates a dog has no assigned team thus belong to the default team of that journey ( every journey has a "default team", regardless the journey has or not team competition )
Just removed as senseless. 
Also "Miembros" field in 'Equipos" Database table is not used. just retained for backward compatibility

Perhaps this issue may be related with this bug:
https://github.com/box/spout/issues/168#issue-127206747

**Comment by nedy13** [comment]
I have seen that you make some Excel related changes. The export function is working.
There is only one small flaw. The printing dialog remains open after the excel is successfully exported. But you easily close the dialog.

Thank you very much for your great support!
